on:
  workflow_dispatch:
    inputs:
      username_to_scrape:
        description: "Twitter Username"
        required: true
        default: "PierreMiniggio"
name: Get tweets
jobs:
  get:
    name: Get tweets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v2
      - run: sudo apt update
      - run: echo $username_to_scrape
        env:
          username_to_scrape: ${{ github.event.inputs.username_to_scrape }}
      - run: git clone --branch fork-master https://github.com/pierreminiggio/selenium-twitter-scraper scraper
      - run : pip --version
      - run: pip install -r scraper/requirements.txt
      - run: python main.py $username_to_scrape $mail $username $password $proxy
        env:
          username_to_scrape: ${{ github.event.inputs.username_to_scrape }}
          mail: ${{ secrets.MAIL }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          proxy: ${{ secrets.PROXY }}
      - uses: actions/upload-artifact@v3
        with:
          name: tweets.json
          path: tweets.json
